source 'https://rubygems.org'


gem 'rails', '4.1.4'
#gem 'sql-lite'

#gem 'pg'
# front end
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'bootstrap-sass', '~> 3.2.0'
gem 'autoprefixer-rails'
gem 'simple_form'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'spring',        group: :development


gem 'annotate'

#testing & debugging tools
group :development do
	gem 'pry-rails'
	gem 'binding_of_caller'
	gem 'better_errors'
	gem 'pry'
	gem 'pry-byebug'
	gem 'thin'
end


gem 'sdoc', '~> 0.4.0',          group: :doc
